#Bank Setup Config

msg-ingame: "&c&lError! &r&7please use this command in-game"
msg-noperms: "&c&lError! &r&7You don't have permission to use this command!"

title: "§5§lWarps"

#MAIN GUIS
#
id: 160
meta: 14
count: 1
#
id1: 160
meta1: 6
count1: 1
#
id2: 160
meta2: 0
count2: 1
#
id3: 160
meta3: 6
count3: 1
#
id4: 160
meta4: 0
count4: 1
#
id5: 160
meta5: 6
count5: 1
#
id6: 160
meta6: 0
count6: 1
#
id7: 160
meta7: 6
count7: 1
#
id8: 160
meta8: 14
count8: 1
#
id9: 160
meta9: 4
count9: 1
#
id10: 160
meta10: 0
count10: 1
#
id11: 54
meta11: 0
name11: "&r&9&l&oCRATE+n+n&r&e-&7 Yêu cầu sức mạnh:+n+n&a- &7&cHP: &720+n+n&a- &fGiáp: 0+n+n&a-&3Dame: 0+n+n&l&3- &eXếp Loại:&a An toàn"
count11: 1
#
id12: 403
meta12: 0
name12: "&r&a&l&oMISSION+n+n&r&e-&7 Yêu cầu sức mạnh:+n+n&a- &7&cHP: &720+n+n&a- &fGiáp: 0+n+n&a-&3Dame: 0+n+n&l&3- &eXếp Loại:&a An toàn"
count12: 1
#
id13: 52
meta13: 0
name13: "&r&c&l&oPVP X BOSSS+n+n&r&e-&7 Yêu cầu sức mạnh:+n+n&a- &7&cHP: &7100+n+n&a- &fGiáp: 80+n+n&a-&3Dame: 45+n+n&l&3- &eXếp Loại:&a Bình thường"
count13: 1
#
id14: 19
meta14: 0
name14: "&r&e&l&oLUCKYBLOCK+n+n&r&e-&7 Yêu cầu sức mạnh:+n+n&a- &7&cHP: &720+n+n&a- &fGiáp: 0+n+n&a-&3Dame: 0+n+n&l&3- &eXếp Loại:&a An toàn"
count14: 1
#
id15: 397
meta15: 0
name15: "&r&b&l&oDUNGEON+n+n&r&e-&7 Yêu cầu sức mạnh:+n+n&a- &7&cHP: &780+n+n&a- &fGiáp: 35+n+n&a-&3Dame: 23+n+n&l&3- &eXếp Loại:&c Nguy Hiểm"
count15: 1
#
id16: 160
meta16: 0
count16: 1
#
id17: 160
meta17: 5
count17: 1
#
id18: 160
meta18: 14
count18: 1
#
id19: 160
meta19: 9
count19: 1
#
id20: 160
meta20: 0
count20: 1
#
id21: 160
meta21: 9
count21: 1
#
id22: 160
meta22: 0
count22: 1
#
id23: 160
meta23: 9
count23: 1
#
id24: 160
meta24: 0
count24: 1
#
id25: 160
meta25: 9
count25: 1
#
id26: 160
meta26: 14
count26: 1
###################
#Button & Command when player click the items
exit-id: 152
exit-meta: 0
msg-teleport: "§c§l> §r§7Đã dịch chuyển thành công !"

###################

#btn-1-id[count]: [item id]
#btn-1-meta[count]: [item meta]
#server_command: [command exuted by player when he clicks the item]

#You Can Add This Up To 20 of these

#warps
btn-1-id11: 54
btn-1-meta11: 0
server_11_command: "warps Crate"
#warps
btn-1-id12: 403
btn-1-meta12: 0
server_12_command: "warps quest"
#warps
btn-1-id13: 52
btn-1-meta13: 0
server_13_command: "warps pvpboss"
#warps
btn-1-id14: 19
btn-1-met14: 0
server_14_command: "warps luckyblock"
#warps
btn-1-id15: 397
btn-1-meta15: 0
server_15_command: "warps dungeon"
#
btn-1-id22: 397
btn-1-meta22: 0
server_22_command: "warps dungeon2"


