---
marker:
  1: 2000
database:
  LetTIHL:
    block: 484
    level: 0
  dbgamingvn2:
    block: 610
    level: 0
  IamVinh5400:
    block: 1782
    level: 0
  ZzremovezZ:
    block: 618
    level: 0
  Jose9543:
    block: 6480
    level: 1
  Kynvn1234:
    block: 1238
    level: 0
  Viethung9204:
    block: 950753
    level: 1
  BuzzingAsh80644:
    block: 332694
    level: 1
  KingOfLmao2380:
    block: 77316
    level: 1
  Nasus1000Q1844:
    block: 91936
    level: 1
  LGB2006:
    block: 139319
    level: 1
  APKKuroTV:
    block: 8944
    level: 1
  DazaiOsamu12333:
    block: 48249
    level: 1
  VinhA6NTT:
    block: 11842
    level: 1
  OffsetAsp489038:
    block: 996
    level: 0
  Boyce1995:
    block: 1176
    level: 0
  ItzMatsterZz:
    block: 2592
    level: 1
  NguyenDongQuy2I:
    block: 122
    level: 0
  Hreinas:
    block: 757
    level: 0
  EverybodysEvery:
    block: 1246
    level: 0
  Quoclam277:
    block: 4086
    level: 1
  DinhBap:
    block: 61244
    level: 1
  Sangking777:
    block: 1956
    level: 0
  LuuVN:
    block: 129
    level: 0
  NuTaVN:
    block: 178
    level: 0
  Ngheo6032:
    block: 2972
    level: 1
  SageGlitter473:
    block: 1127
    level: 0
  AnhNghok:
    block: 323
    level: 0
  Datsiudz:
    block: 50448
    level: 1
  NgocMaiHp:
    block: 4596
    level: 1
  Oren4845:
    block: 169
    level: 0
  ductoan123:
    block: 1
    level: 0
  ditconmemay0411:
    block: 2202
    level: 1
  Thaiday123:
    block: 11448
    level: 1
  KingknightVN:
    block: 101522
    level: 1
  MinhTrnggem:
    block: 148365
    level: 1
  khoikage1:
    block: 1341
    level: 0
  SpeedierYak4029:
    block: 739
    level: 0
  Dcmhunglon:
    block: 19
    level: 0
  shbdbd:
    block: 5687
    level: 1
  Binhdepgai:
    block: 1353
    level: 0
  VietCrisaz:
    block: 7312
    level: 1
  DeathSwar79:
    block: 51529
    level: 1
  BinGamine:
    block: 729
    level: 0
  Bom Fake:
    block: 378
    level: 0
  NobiGaming07:
    block: 457
    level: 0
  HaiTieuPhu9423:
    block: 50
    level: 0
  Theherono123:
    block: 92
    level: 0
  SixKoala8019590:
    block: 73
    level: 0
  PuckVN:
    block: 0
    level: 0
  WaterNe7261:
    block: 117
    level: 0
  streamerpro:
    block: 109
    level: 0
  tuongvu2007:
    block: 80
    level: 0
  SheaZ2101:
    block: 2634
    level: 1
  TuiDepTraiii:
    block: 29
    level: 0
  idolbminh:
    block: 83
    level: 0
  ZxKillerxZ1753:
    block: 103
    level: 0
  LanNg03:
    block: 357
    level: 0
  MrDane07:
    block: 313
    level: 0
  kotorireal:
    block: 248
    level: 0
  SenGaoTV:
    block: 2651
    level: 1
  KhangHoangDZ:
    block: 154
    level: 0
  VoThan091:
    block: 73
    level: 0
  RapidestAsh5795:
    block: 59
    level: 0
  HungXoaSv:
    block: 56
    level: 0
  Outwither boy:
    block: 837
    level: 0
  AboutRocket6107:
    block: 14
    level: 0
  SeaLonggaming:
    block: 72
    level: 0
  Cuongplayyer:
    block: 22
    level: 0
  VisedMink584354:
    block: 8507
    level: 1
  MapNeee:
    block: 384295
    level: 1
  HaiTieuPhu:
    block: 35
    level: 0
  NhanAZ:
    block: 109
    level: 0
  cunvipvcl:
    block: 14576
    level: 1
  vjp pr0:
    block: 10
    level: 0
  ZzTrig:
    block: 40
    level: 0
  panhbao:
    block: 17
    level: 0
  MonsieurHac:
    block: 5791
    level: 1
  MAX10058648:
    block: 2950
    level: 1
  SappyPlanet1400:
    block: 17993
    level: 1
  PeakRedLine99:
    block: 2253
    level: 1
  NgMKhang:
    block: 675
    level: 0
  EntityN2067:
    block: 1916
    level: 0
  Taizaxua5652:
    block: 19
    level: 0
  haorz123:
    block: 252
    level: 0
  Carochien:
    block: 257
    level: 0
  Vanh6666:
    block: 0
    level: 0
  Phau7287936:
    block: 86
    level: 0
  AlarmedAtol5816:
    block: 2991
    level: 1
  RathMeowGay:
    block: 0
    level: 0
  ToyTenDuong:
    block: 51
    level: 0
  MonTersfood:
    block: 16401
    level: 1
  Hoangtran26:
    block: 3153
    level: 1
  banhmi Deeeee:
    block: 23
    level: 0
  Tranminhpro2630:
    block: 18
    level: 0
  Linar2635:
    block: 10
    level: 0
  CDanh0206:
    block: 51
    level: 0
  Khanhuwu3200:
    block: 9
    level: 0
  UnearnedLime34:
    block: 103
    level: 0
  RomNoPro:
    block: 8
    level: 0
  ForbidPoem2799:
    block: 71
    level: 0
  Kingoros3599:
    block: 1182
    level: 0
  Kabuto29992:
    block: 202
    level: 0
  Jesnaes1:
    block: 1
    level: 0
  FocusedBirch228:
    block: 651
    level: 0
  VG4803:
    block: 281
    level: 0
  Geox c3:
    block: 1090
    level: 0
...
