# Thanks for downloading SimpleAnnouncements and adding it to your server!
# Here is the base configuration file for the plugin

# This is the text that would appear st the top and bottom when using the
# /announce command
announcement-text: "§4├------------§9 ↠ §6§lAnnouncement§r§9 ↞ §4------------┤"

# The text that shows in the middle of the two announcement texts you set above
# Formatting codes can be found at https://minecraft.fandom.com/wiki/Formatting_codes#Color_codes
# {PLAYER} is automatically swapped out for the player who ran the command
# {MESSAGE} is the message (text) part of the command (/announce <message:text>)
middle-text: "§l§aServer:§r {MESSAGE}"

# If you change this part the plugin may not work
# ONLY CHANGE THIS IF THE PLUGIN TOLD YOU TO
config-version: 1.0.1
