# Variables:
# %player% - player frozen
# %arg% - Command argument on error  - Not supported yet

# Enable auto bans? Set to true if you want this enabled.
autoban: true
# Message that displays in chat (use %player%)
autoban-msg: "§e%player% §fđã §cbị cấm§f bởi vì họ đã đăng xuất trong khi bị đóng băng."
# Message that displays for player.
autoban-reason: "§cYou are banned for: §bLogging out while frozen"
# Format for freeze.
format: "§l[§bFreeze-§eMine§aSuon§f])§r "
# Allow commands while frozen? Default is false (No)
commands-frozen: false
# Allow frozen player to attack? Default is false
attack-frozen: false
# Allow frozen player to be attacked? Default is false
attacked-frozen: false
# Allow frozen players to use /msg and such? Default is true (true = allow /msg 's)
dms-frozen: true
# Frozen tag Defaults to true, if false, normal player tag will be shown.
frozen-tag: true
# Frozen message, aka when frozen (one time)
frozen-msg: true
# Text next to player name while frozen
format-tag: "§b§lFROZEN §r§l- §aмιɴᴇ§esuoɴ"
# Frozen title message
title-msg: true
# Frozen actionbar message
action-msg: true
# Timer - Idea, not made yet.
timer: 300 # 5 minutes
timer-after: "autoban" # autoban false kick warn

# MESSAGES  - Set each to false to disable the feature entirely (If not a setting above^)
error-hit: "§cBạn không thể đánh người chơi khác khi bị đóng băng." # Supported
error-attack: "§cBạn không thể đánh người chơi bị đóng băng" # Supported
error-noperm: "§cMissing permissions: freeze or freeze.command" # Unsupported
error-frozen: "§cNgười chơi này đã bị đóng băng" # Supported
error-frozen-msg: "§cBây giờ bạn đã bị đóng băng! Hãy xem lại tội lỗi của mình!."
error-immune: "§cNgười chơi này được miễn nhiễm." # Supported
error-provideArgument: "§cError, provide a §e%arg%"
error-player: "§cCould not find player: §e%arg%" # Unsupported
error-onjoin: "§cBạn bị đóng băng" # Supported
error-title: "§cBạn đã bị đóng băng" # Supported
error-actionbar: "§cDo not log out" # Supported
