---
# This plugin was made by DaRealAqua with Love^_^
#
# LexusPE Network Discord: http://discord.lexuspe.xyz/
#
# CONTACT ME ON:
# Discord: DaRealAqua#9324
# Twitter: LexusPE_Network
# Instagram: 16_aero
#
# How to create a tag:
# tags:
#   tagName:
#     name: "nameColored"
#     perm: "Permission"
#     cost: "amount$$"
#
# Tags: {line}, {point}, {tag}, {costp}, {player}, {permission}

# Display the tag of the player
chat-format: "{tag} {player}"

# Tags List
tags:
  cute:
    name: "§f[§l§c❤ §aCute §c❤§f]§r"
    perm: cute.tag
    costp: 15
  partner:
    name: "§l§b[§ePartner §d✉§b]§r"
    perm: partner.tag
    costp: 15
  boss:
    name: "§l§b[§cBoss §6♛§b]§r"
    perm: boss.tag
    costp: 15
  toiuuhoa:
    name: "§l§b[§3Optimization §a✔§b]§r"
    perm: optimize.tag
    costp: 15

# Main menu of the Tags Menu
# Category Selector Menu
menu-selector:
  title: "§l§3• §aBiệt danh §l§3•"
  content: "§l§3• §fPoint của bạn:§c {point}§e Point{line}§l§3• §fBiệt danh của bạn:§c {tag}{line}§r§a---Tùy chọn mục dưới đây---"
  tags-button: "§l§3• §eChọn biệt danh §l§3•"
  shop-button: "§l§3• §bMua biệt danh §l§3•"
  exit-button: "§l§cThoát"
# Equip the tag u want, if you have the permission
# Tags Menu
menu-tags:
  title: "§l§3• §aBiệt danh §l§3•"
  content: "{line}§l§3• §fBiệt danh của bạn:§c {tag}{line}{line}"
  locked-button: "{tag}{line}§r§cKhông có"
  unlocked-button: "{tag}{line}§r§aĐã có"
# Buy a tag
# Tags Shop Menu
menu-shop:
  title: "§l§3• §bMua biệt danh §l§3•"
  content: "§l§3• §fPoint của bạn:§c {point}§e Point"
  button: "{tag}{line}§l§3• §c{costp} §ePoint"
  # PureChat and PurePerm I currently use to set a player's permission but if you want you can use your own plugin.
  command: "setuperm {player} {permission}"
...
