---
# KygekRanksUI plugin
# Made by Kygekraqmak

##### DANGER ZONE #####
# Do not change this (Only for internal use)!
config-version: 1.3
# If you encounter bugs set this to true to reset the config!
reset: false
#######################

# Use "{player}" to show player's name
# Use "&" as formatting codes
# Use "\n" to break into new line

##### COMMANDS #####
# Set the command description of KygekRanksUI
# Leave it empty if you want to use the default description
command-description: ""
# Set command aliases that will open KygekRanksUI when executed (Default command will always be /ranks)
# Do not use "/" in front of the commands!
# Leave it empty if you don't want to use aliases
command-aliases: [quyenrank]
####################

# Title of the main form of KygekRanksUI
# It will be shown right after the player typed the /ranks command
title: "§l§cRankUI"
# Content of the main form of KygekRanksUI
# You can add general info about the ranks below
content: ""
# Return button to the main form of KygekRanksUI
# It will be shown in the ranks form and applied globally
return-button: "Return"
# Exit button in the main form of KygekRanksUI
exit-button: "Exit"
# Whether to return to main form when ranks form closed (X button at upper right corner)
return-to-main: true

##### RANKS FORM FORMAT #####
# ranks:                                              --> You will put the ranks menu button, title and content below here.
#   ExampleRank:                                      --> This will just be the identifier for the code to work. You can put anything you like.
#     menu-button: "ExampleRank"                      --> This will be the button of the rank that will be shown in the main form.
#     button-image: "https://example.com/example.png" --> This will be the image shown beside the button in the main form.
#     title: "ExampleRank"                            --> This will be the title of the rank that will be shown in the rank's form.
#     content: "Change in config.yml!"                --> This will be the content of the rank that will be shown in the rank's form.
#############################

# Notes for button-image (not following this may not load the image):
#
# There are 2 modes (texture pack or link). If you want to use image from link, you must follow below:
# - Image should be using the .png format.
# - Image should be 160 x 160 px in size.
# - Image should be displayed as raw (no HTML/CSS/JavaScript included).
# - Link should include "http://" or "https://".
# - Sometimes the image will not load properly, you may have to open status bar or press Windows key.
# - For example, please visit https://kygekraqmak.github.io/downloads/css/test.png.
#
# If you want to use image from texture pack, please visit https://github.com/Kygekraqmak/default-textures for more info.
#
# Leave button-image empty if you don't want to use any image(s).

# Change here:
ranks:
  Rank1:
    menu-button: "§f⚔ §7- §6【§b§lPlus§r§6】 §7- §f⚔"
    button-image: "https://img.icons8.com/dusk/2x/soccer-yellow-card.png"
    title: "§f⚔ §7- §6【§b§lPlus§r§6】 §7- §f⚔"
    content: "§7-----------------------------\n\n§3• §6Đặc Quyền §3• §7\n\n----------------------------\n\n§3• §6Fly:§7 Có chức năng dùng để bay\n\n§3• §6HealFeed: §7Dùng để hồi phục thể lực\n\n§7-----------------------------\n\n"
  Rank2:
    menu-button: "§f⚔ §7- §6【§b§lPlus §e+§r§6】 §7- §f⚔"
    button-image: "https://img.icons8.com/dusk/2x/soccer-yellow-card.png"
    title: "§f⚔ §7- §6【§b§lPlus §e+§r§6】 §7- §f⚔"
    content: "§7-----------------------------\n\n§3• §6Đặc Quyền §3• §7\n\n----------------------------\n\n§3• §6Fly:§7 Có chức năng dùng để bay\n\n§3• §6HealFeed: §7Dùng để hồi phục thể lực\n\n§3• §6Teleport:§7 có chức năng dùng để dịch chuyển tới chỗ người khác\n\n§7-----------------------------\n\n"
  Rank3:
    menu-button: "§d⚜ §7- §6【§c§lMVP §e+§r§6】 §7- §d⚜"
    button-image: "https://img.icons8.com/dusk/2x/soccer-yellow-card.png"
    title: "§d⚜ §7- §6【§c§lMVP §e+§r§6】 §7- §d⚜"
    content: "§7-----------------------------\n\n§3• §6Đặc Quyền §3• §7\n\n----------------------------\n\n§3• §6Fly:§7 Có chức năng dùng để bay\n\n§3• §6HealFeed: §7Dùng để hồi phục thể lực\n\n§3• §6Size:§7 có chức năng chỉnh size người chơi\n\n§3• §6Teleport:§7 có chức năng dùng để dịch chuyển tới chỗ người khác\n\n§7-----------------------------\n\n"
  Rank4:
    menu-button: "§3⊱⊰ §7- §6【§e§lPremium§r§6】 §7- §3⊱⊰"
    button-image: "https://img.icons8.com/dusk/2x/soccer-yellow-card.png"
    title: "§3⊱⊰ §7- §6【§e§lPremium§r§6】 §7- §3⊱⊰•"
    content: "§7-----------------------------\n\n§3• §6Đặc Quyền §3• §7\n\n----------------------------\n\n§3• §6Fly:§7 Có chức năng dùng để bay\n\n§3• §6HealFeed: §7Dùng để hồi phục thể lực\n\n§3• §6Size:§7 có chức năng chỉnh size người chơi\n\n§3• §6Vanish:§7 có chức năng tàn hình ẩn danh\n\n§3• §6Teleport:§7 có chức năng dùng để dịch chuyển tới chỗ người khác\n\n§7-----------------------------\n\n"
  Rank5:
    menu-button: "§6✉ §7- §5❖ §9§lPlatinum §4+§r §5❖ §7- §6✉"
    button-image: "https://img.icons8.com/dusk/2x/soccer-yellow-card.png"
    title: "§6✉ §7- §5❖ §9§lPlatinum §4+§r §5❖ §7- §6✉"
    content: "§7-----------------------------\n\n§3• §6Đặc Quyền §3• §7\n\n----------------------------\n\n§3• §6Fly:§7 Có chức năng dùng để bay\n\n§3• §6HealFeed: §7Dùng để hồi phục thể lực\n\n§3• §6Effect:§7 có chức năng dùng effect miễn phí\n\n§3• §6Size:§7 có chức năng chỉnh size người chơi\n\n§3• §6Vanish:§7 có chức năng tàn hình ẩn danh\n\n§3• §6Teleport:§7 có chức năng dùng để dịch chuyển tới chỗ người khác\n\n§7-----------------------------\n\n"
  # You can add more if you need by following the format above

# Whether to check for plugin updates (Recommended)
check-updates: true
...
