---
show-messages-onjoin: true
force-hub: false
enable-hub-message: true
force-spawn: false
enable-spawn-message: true
enable-aliases: true
teleport-on-death: 1
hub-server:
  enabled: false
  name: External Server
  host: 127.0.0.1
  port: 19132
hub:
  world: world
  X: -7.388400
  "Y": 30.000000
  Z: -120.581000
  Yaw: 213.940491
  Pitch: 2.797241
...
