---
version: 1.4.10-6
default-factions-plugin: FactionsPro
enable-multiworld-chat: false
groups:
  Guest:
    chat: §l§f[§b{suffix}§f] §l§6♛§d•§3{fac_name}§d•§6♛ §l§7• §r§fMember §l§7• §r§f{display_name} §l§c››
      §r§f{msg} §l§c‹‹
    nametag: §l§6♛§d•§3{fac_name}§d•§6♛ §l§7• §r§fMember §l§7• §r§f{display_name}
    worlds: []
  Admin:
    chat: §l§f[§b{suffix}§f] §l§6♛§d•§3{fac_name}§d•§6♛ §l§7• §r§fMember §l§7• §r§f{display_name} §l§c››
      §r§f{msg} §l§c‹‹
    nametag: §l§6♛§d•§3{fac_name}§d•§6♛ §l§7• §r§fMember §l§7• §r§f{display_name}
    worlds: []
  Owner:
    chat: §l§f[§b Bê đê §f]§l§6♛§3{fac_name}§6♛ §a✪§dOWNER§a✪ §b• §eミ★§a{display_name}§e★彡 §6♪§d{msg}§6♪
    nametag: '§l§6♛§3{fac_name}§6♛ §a✪§dOWNER§a✪ §b• §eミ★§a{display_name}§e★彡 '
    worlds: []
  OP:
    nametag: '[OP] §r§b{display_name}'
    chat: '[§e§l❖c︵§aO§dP§c︵§e❖§r] §l§e{display_name} §b→ §c{msg}'
    worlds: []
  Vip1:
    nametag: §l§6♛§d•§3{fac_name}§d•§6♛ §l§d• §aミ★§eVIP-§6I§a★彡 §d• §r§a{display_name}
    chat: §l§6♛§d•§3{fac_name}§d•§6♛ §l§d• §aミ★§eVIP-§6I§a★彡 §d• §r§a{display_name}
      §l§c›› §r§e{msg} §l§c‹‹
  Vip2:
    nametag: §l§6♛§d•§3{fac_name}§d•§6♛ §l§d• §aミ★§eVIP-§6II§a★彡 §d• §r§a{display_name}
    chat: §l§6♛§d•§3{fac_name}§d•§6♛ §l§d• §aミ★§eVIP-§6II§a★彡 §d• §r§a{display_name}
      §l§c›› §r§e{msg} §l§c‹‹
  Vip3:
    nametag: §l§6♛§d•§3{fac_name}§d•§6♛ §l§d• §aミ★§eVIP-§6III§a★彡 §d• §r§a{display_name}
    chat: §l§6♛§d•§3{fac_name}§d•§6♛ §l§d• §aミ★§eVIP-§6III§a★彡 §d• §r§a{display_name}
      §l§c›› §r§e{msg} §l§c‹‹
  Vip4:
    nametag: §l§6♛§d•§3{fac_name}§d•§6♛ §l§d• §aミ★§eVIP-§6IV§a★彡 §d• §r§a{display_name}
    chat: §l§6♛§d•§3{fac_name}§d•§6♛ §l§d• §aミ★§eVIP-§6IV§a★彡 §d• §r§a{display_name}
      §l§c›› §r§e{msg} §l§c‹‹
  Vip5:
    nametag: §l§6♛§d•§3{fac_name}§d•§6♛ §l§d• §aミ★§eVIP-§6V§a★彡 §d• §r§a{display_name}
    chat: §l§6♛§d•§3{fac_name}§d•§6♛ §l§d• §aミ★§eVIP-§6V§a★彡 §d• §r§a{display_name}
      §l§c›› §r§e{msg} §l§c‹‹
  police:
    chat: '§l§f[§b{suffix}§f] §l§c♦ §f{fac_name} §c♦ §l§e• §1Police §l§e• §c↣ §f{display_name} §r: §l§e{msg}'
    nametag: §l§c♦ §f{fac_name} §c♦ §l§e• §1Police §l§e• §c↣ §f{display_name}
  helper:
    chat: '§l§f[§b{suffix}§f] §l§c♦ §f{fac_name} §c♦ §l§e• §dHelper §l§e• §c↣ §f{display_name} §r: §l§f{msg}'
    nametag: §l§c♦ §f{fac_name} §c♦ §l§e• §dHelper §l§e• §c↣ §f{display_name}
  vip1:
    nametag: §l§c♦ §e[§f{fac_name}§e] §c♦ §l§e• §b★ §2Vip§6I §b★ §l§e• §c↣ §f{display_name}
    chat: '§l§c♦ §e[§f{fac_name}§e] §c♦ §l§e• §b★ §2Vip§6I §b★ §l§e• §c↣ §f{display_name}
      §r: §l§e{msg}'
  vip3:
    nametag: §l§c♦ §e[§f{fac_name}§e] §c♦ §l§e• §b★ §2Vip§6III §b★ §l§e• §c↣ §f{display_name}
    chat: '§l§c♦ §e[§f{fac_name}§e] §c♦ §l§e• §b★ §2Vip§6III §b★ §l§e• §c↣ §f{display_name}
      §r: §l§e{msg}'
  vip2:
    chat: '§l§c♦ §e[§f{fac_name}§e] §c♦ §l§e• §b★ §2Vip§6II §b★ §l§e• §c↣ §f{display_name}
      §r: §l§e{msg}'
    nametag: §l§c♦ §e[§f{fac_name}§e] §c♦ §l§e• §b★ §2Vip§6II §b★ §l§e• §c↣ §f{display_name}
  vip4:
    chat: '§l§c♦ §e[§f{fac_name}§e] §c♦ §l§e• §b★ §2Vip§6IV §b★ §l§e• §c↣ §f{display_name}
      §r: §l§e{msg}'
    nametag: §l§c♦ §e[§f{fac_name}§e] §c♦ §l§e• §b★ §2Vip§6IV §b★ §l§e• §c↣ §f{display_name}
  vip5:
    chat: '§l§c♦ §e[§f{fac_name}§e] §c♦ §l§e• §b★ §2Vip§6V §b★ §l§e• §c↣ §f{display_name}
      §r: §l§e{msg}'
    nametag: §l§c♦ §e[§f{fac_name}§e] §c♦ §l§e• §b★ §2Vip§6V §b★ §l§e• §c↣ §f{display_name}
  vip6:
    nametag: '&8&l[vip6]&f&r {display_name}'
    chat: '&8&l[vip6]&f&r {display_name} &7> {msg}'
  Plus:
    chat: '§l§f[§b{suffix}§f] §e『§a{fac_name}§e』 §f⚔ §7- §6【§b§lPlus§r§6】 §7- §f⚔ §9{display_name}: §3{msg}'
    nametag: §e『§a{fac_name}§e』 §f⚔ §7- §6【§b§lPlus§r§6】 §7- §f⚔ §9{display_name}
  PLus1:
    chat: '§l§f[§b{suffix}§f] §e『§a{fac_name}§e』 §f⚔ §7- §6【§b§lPlus §e+§r§6】 §7- §f⚔ §9{display_name}:
      §3{msg}'
    nametag: §e『§a{fac_name}§e』 §f⚔ §7- §6【§b§lPlus §e+§r§6】 §7- §f⚔ §9{display_name}
  mvp:
    chat: '§l§f[§b{suffix}§f] §e『§a{fac_name}§e』 §d⚜ §7- §6【§c§lMVP§r§6】 §7- §d⚜ §9{display_name}: §3{msg}'
    nametag: §e『§a{fac_name}§e』 §d⚜ §7- §6【§c§lMVP§r§6】 §7- §d⚜ §9{display_name}
  mvpplus:
    chat: '§l§f[§b{suffix}§f] §e『§a{fac_name}§e』 §d⚜ §7- §6【§c§lMVP §e+§r§6】 §7- §d⚜ §9{display_name}:
      §3{msg}'
    nametag: §e『§a{fac_name}§e』 §d⚜ §7- §6【§c§lMVP §e+§r§6】 §7- §d⚜ §9{display_name}
  premium:
    chat: '§l§f[§b{suffix}§f] §e『§a{fac_name}§e』 §3⊱⊰ §7- §6【§e§lPremium§r§6】 §7- §3⊱⊰ §c{display_name}:
      §a{msg}'
    nametag: §e『§a{fac_name}§e』 §3⊱⊰ §7- §6【§e§lPremium§r§6】 §7- §3⊱⊰ §c{display_name}
  Investor:
    chat: '§l§f[§b{suffix}§f] §e⇱§a{fac_name}§e⇲ §3⊱⊰ §7- §6【§3§lInvestors Server§r§6】 §7- §3⊱⊰ §a{display_name}:
      §e{msg}'
    nametag: §e⇱§a{fac_name}§e⇲ §3⊱⊰ §7- §6【§3§lInvestors Server§r§6】 §7- §3⊱⊰ §a{display_name}
  platinum:
    chat: '§l§f[§b{suffix}§f] §e⇱§a{fac_name}§e⇲ §6✉ §7- §5❖ §9§lPlatinum §4+§r §5❖ §7- §6✉ §a{display_name}:
      §e{msg}'
    nametag: §e⇱§a{fac_name}§e⇲ §6✉ §7- §5❖ §9§lPlatinum §4+§r §5❖ §7- §6✉ §a{display_name}
  NgauLoi:
    nametag: '&8&l[NgauLoi]&f&r {display_name}'
    chat: '&8&l[NgauLoi]&f&r {display_name} &7> {msg}'
  Streamer:
    nametag: '&8&l[Streamer]&f&r {display_name}'
    chat: '&8&l[Streamer]&f&r {display_name} &7> {msg}'
  Server:
    nametag: '&8&l[Server]&f&r {display_name}'
    chat: §d[Server] {msg}
  PhatToOnline:
    chat: §l§6 Phật Sống ONLINE §r> §e{msg}
    nametag: .
  OngBut:
    chat: §l§o§c♠ EVENT ♠ §a→ §e{msg}
    nametag: '&8&l[OngBut]&f&r {display_name}'
  Huan:
    chat: §l§b Huấn Hoa§d Hường §r§a> {msg}
    nametag: '&8&l[Huan]&f&r {display_name}'
  xaydung:
    chat: '§l§f[§b{suffix}§f] §l§3『§4{fac_name}§3』§a‣ §6• §7- §aBuilder §7- §6• §e⚒§r§f {display_name}:
      §e{msg}'
    nametag: §l§3『§4{fac_name}§3』§a‣ §6• §7- §aBuilder §7- §6• §e⚒§r§f {display_name}
  BaTan:
    nametag: '&8&l[BaTan]&f&r {display_name}'
    chat: §o§cZ§dz§eremove§dz§cZ • §l§e{msg}
  Crafter:
    chat: §l§c• §e{fac_name} §l§c• §b↦ §3• §fCraf§eter §3• §d✿ §a{display_name}:§l§f
      {msg}
    nametag: '&8&l[Crafter]&f&r {display_name}'
  Bede:
    nametag: '&8&l[Bede]&f&r {display_name}'
    chat: §l§d {display_name} → Tui là con gái nha §r§a→ {msg}
  Occho:
    chat: §l§e{display_name} §r→§a Tao bị ngu uuuu !
    nametag: '&8&l[Occho]&f&r {display_name}'
  admin:
    nametag: '&8&l[admin]&f&r {display_name}'
    chat: '&8&l[admin]&f&r {display_name} &7> {msg}'
  zzremovezz:
    chat: '{fac_name} {dis_player} •{msg}'
    nametag: '&8&l[zzremovezz]&f&r {display_name}'
  occho:
    chat: §l§eOcChoNhatSv §r• §l§d{msg}
    nametag: '&8&l[occho]&f&r {display_name}'
  Police:
    chat: §l§f[§b{suffix}§f] §l§c♦ §f{fac_name}§c ♦ §b• §aPOLICE §e+§b •§c → §r{display_name} §a→ {msg}
    nametag: §l§aPOLICE §c+ §b{display_name}
...
