---
datetime-format: "H:i:s"
Motd:
  update-timeout: 1
  custom: true
  message: "§l§a[§6AIS§a]§c ˃ §eMine§aSuon"
OutdatedClient:
  custom: true
  message: "§cThe server has now been upgraded to 1.17, requesting a new download"
OutdatedServer:
  custom: true
  message: "§cThe server has now been upgraded to 1.17, requesting a new download"
WhitelistedServer:
  custom: true
  message: "§fBảo trì ..... <3!!"
FullServer:
  custom: true
  message: "§eServer đã đầy vui lòng vào lại sau"
FirstJoin:
  enable: true
  message: "§l§e{PLAYER} §dđã tham gia server lần đầu §6U^ｪ^U  "
Join:
  hide: false
  custom: true
  message: "§l§e{PLAYER} §dđã tham gia máy chủ §6U^ｪ^U §b•"
Quit:
  hide: false
  custom: true
  message: "§l§e{PLAYER} §dtạm thoát máy chủ để nghĩ ngơi §6◖⚆ᴥ⚆◗ §b•"
WorldChange:
  enable: false
  message: "&e{PLAYER}&b đã dịch chuyển"
Death:
  hide: false
  custom: true
  message: "§7{PLAYER} chết"
  death-contact-message:
    hide: false
    custom: true
    message: "§7{PLAYER} Nghẹt thở mà chết"
  kill-message:
    hide: false
    custom: true
    message: "§7⚔️ {KILLER} đã giết chết {PLAYER}"
  death-projectile-message:
    hide: false
    custom: true
    message: "§7{KILLER} đã bắn chết {PLAYER}"
  death-suffocation-message:
    hide: false
    custom: true
    message: "§7{PLAYER} Nghẹn thở mà chết"
  death-fall-message:
    hide: false
    custom: true
    message: "§7{PLAYER} rơi từ nơi cao"
  death-fire-message:
    hide: false
    custom: true
    message: "§7{PLAYER} bị thiêu sống"
  death-on-fire-message:
    hide: false
    custom: true
    message: "§7{PLAYER} bị thiêu sống"
  death-lava-message:
    hide: false
    custom: true
    message: "&7{PLAYER} đang bơi trong LAVA chết"
  death-drowning-message:
    hide: false
    custom: true
    message: "§7{PLAYER} chết đuối"
  death-explosion-message:
    hide: false
    custom: true
    message: "§7{PLAYER} phát nổ"
  death-void-message:
    hide: false
    custom: true
    message: "§7{PLAYER} rơi vào chân không"
  death-suicide-message:
    hide: false
    custom: true
    message: "§7{PLAYER} tự tử"
  death-magic-message:
    hide: false
    custom: true
    message: "§7{PLAYER} chết do thuốc độc"
...