hptext: "§l§a+ §e1§c♥\n§7§l- §e50§a☘"
#edit for easy ;)
hpimage: "https://img.icons8.com/flat-round/2x/hearts.png"

giaptext: "§l§a+ §e1§b▼\n§7§l- §e100§a☘"
#thissssssssssssssssssssssssss
giapimage: "https://img.icons8.com/dusk/2x/shield.png"

dametext: "§l§a+ §e1§c⚔\n§7§l- §e75§a☘" #text only
#-----------------------
dameimage: "https://img.icons8.com/fluent/2x/sparring.png"

#----
exittext: "§l§c✘"
exitimage: "https://img.icons8.com/color/2x/close-window.png"
#08i894ritju3o9i4oe8rikfj
hoabinhtext: "§l§a⊕"
hoabinhimage: "https://img.icons8.com/fluent/2x/peace-pigeon.png"
pvptext: "§l§c✘"
pvpimage: "https://img.icons8.com/color/2x/iron-age-warrior.png"
