uptext: "§r§l§c● §dNâng Cấp §l§c●"
upimage: "https://img.icons8.com/fluent/2x/approve-and-update.png"
exittext: "§l§cThoát"
exitimage: "https://img.icons8.com/color/2x/close-window.png"
up2text: "§r§l§c● §dPhá bỏ limited §l§c●"
up2image: "https://img.icons8.com/fluent/2x/development-skill.png"