---
language: english
debug: false
discord: true
pureperms: false
factions: false
banned_list:
- '@here'
- '@everyone'
webhook_url: https://discord.com/api/webhooks/818782343917600768/-sozE1vBZ9UVt6nGC3s53Xqe_jOC9DwvrnSEj_kQSb0BytHGJ52IF5J9Cg147wu3XHvk
webhook_name: ToPLay
webhook_playerChat?: true
webhook_playerJoin?: true
webhook_playerLeave?: true
webhook_playerDeath?: true
webhook_playerChatFormat: '{player} : {msg}'
webhook_playerJoinFormat: '{player} Joined the server !'
webhook_playerLeaveFormat: '{player} Left the server !'
webhook_playerDeathFormat: '{player} Died !'
other_pluginEnabled?: true
other_pluginDisabled?: true
other_pluginEnabledFormat: Plugin Enabled !
other_pluginDisabledFormat: Plugin Disabled !
...
