#--------HelpUI----------
#edit in config :)
#Links Image: icons8.com

#Menu
#button1
start1: "§l§6Bắt Đầu Ngay Thôi Nào" #font
start: "https://img.icons8.com/color/2x/start.png" #link image
#button2
help1: "§l§6Trợ giúp trong cho người chơi"
help: "https://img.icons8.com/fluent/2x/help.png"
#button3
rules1: "§l§6Xem luật của server"
rules: "https://img.icons8.com/dusk/2x/rules.png"
#helpmenu
#button1
back1: "§l§6Trở lại"
back: "https://img.icons8.com/color/2x/close-window.png"
#button2
helpcmd: "§l§cThông tin lệnh"
helpcmd1: "https://img.icons8.com/fluent/2x/info.png"
#button3
helpdungeon1: "§l§eThông tin Dungeon"
helpdungeon: "https://img.icons8.com/windows/2x/Dungeon.png"
#button4
chisochu1: "§l§0Thông tin chỉ số"
chisoanh1: "https://img.icons8.com/dusk/2x/overview-pages-4.png"


