name: AutoFMReset
main: AndreasHGK\AutoMineReset\Main
version: 0.3.4
api: [3.0.0]
load: POSTWORLD
author: [Nameless, NhanAZ]
description: Tự Động Lắp Đầy Toàn Bộ Khu Mỏ Khai Thác Sau Mỗi Khoảng Thời Gian Nhất Định!
commands:
 mrs:
  description: "Lắp Đầy Toàn Bộ Khu Mỏ Khai Thác!"
  usage: "/mrs"
  permission: mineresets.command.resetall
 autoreset:
  description: "Bật Hoặc Tắt Tính Năng Tự Động Lắp Đầy Toàn Bộ Khu Mỏ Khai Thác!"
  usage: "/autoresets"
  permission: amrs.autoreset
