# MADE BY:
#  __    __                                          __        __  __  __
# /  |  /  |                                        /  |      /  |/  |/  |
# $$ |  $$ |  ______   _______    ______    ______  $$ |____  $$/ $$ |$$/   _______  __    __
# $$  \/$$/  /      \ /       \  /      \  /      \ $$      \ /  |$$ |/  | /       |/  |  /  |
#  $$  $$<  /$$$$$$  |$$$$$$$  |/$$$$$$  |/$$$$$$  |$$$$$$$  |$$ |$$ |$$ |/$$$$$$$/ $$ |  $$ |
#   $$$$  \ $$    $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |$$ |$$ |$$ |      $$ |  $$ |
#  $$ /$$  |$$$$$$$$/ $$ |  $$ |$$ \__$$ |$$ |__$$ |$$ |  $$ |$$ |$$ |$$ |$$ \_____ $$ \__$$ |
# $$ |  $$ |$$       |$$ |  $$ |$$    $$/ $$    $$/ $$ |  $$ |$$ |$$ |$$ |$$       |$$    $$ |
# $$/   $$/  $$$$$$$/ $$/   $$/  $$$$$$/  $$$$$$$/  $$/   $$/ $$/ $$/ $$/  $$$$$$$/  $$$$$$$ |
#                                         $$ |                                      /  \__$$ |
#                                         $$ |                                      $$    $$/
#                                         $$/                                        $$$$$$/
VERSION: "1.4.0" # Internal use only


Default:
  # Choose whether new Smaccers and existing ones without explicit instruction should spin
  # This can be false or a float as a speed setting
  spin: false
  # This is the default cooldown time (in seconds) that new or unset Smaccers will have
  # Set this to 0 for no cooldown
  cooldown: 0.5
  # Choose whether new Smaccers and existing ones without explicit instruction should have SlapBack enabled
  # This option can be true or false
  slap: true
  # This is the default nametag that will appear when you create a new Smaccer entity
  # Available tags:
  # {player} use the player's name
  spawn-name: ""
  # This is the interval time (in ticks) that the query task will execute for server player counts
  # Default is 200 ticks (10 seconds)
  query-interval: 200
  # This adds the ability to show player counts on Smaccer nametags
  count-tags:
    # This is the format that will be used for showing the amount of players on a world (or multiple)
    # Available tags:
    # {players} shows total world player count
    worlds: "§a{players} §eonline"
    # This is the format that will be used for showing the amount of players on a server (or multiple)
    # Available tags:
    # {players} shows total server player count
    # {maximum} shows player cap for the server
    servers: "§a{players}§7/§c{maximum}"

# Set these add-ons to true or false to enable or disable their features (respectively)

# SlapBack allows Smaccers to hit you back
SlapBack:
  enabled: false

# SlapperRotation allows nearby Smaccers to look at you
SlapperRotation:
  enabled: false
  # This is the maximum distance that a Smaccer will target another player
  max-distance: 16

# SlapperCache allows you to cache or uncache Smaccers
SlapperCache:
  enabled: false

# SlapperPlus gives you an easy UI for managing Smaccers
SlapperPlus:
  enabled: false

# SlapperCooldown limits how fast a Smaccer can be hit
SlapperCooldown:
  enabled: false
  # This is the message sent when a player attempts to hit a Smaccer too quickly
  message: "§aYou're hitting me too fast!"