keys:
  id: 131
  meta: 0
  name: "§l§3• §2Key §e{CRATE} §3•"
  lore: ""
crates:
  # Options: instant, roulette
  mode: instant
  roulette:
    # Minimum duration: (duration/speed) >= 5.5
    # If (duration/speed) ends up being less than 5.5, then your default time will be set to (6*speed)
    duration: 30
    # Minimum speed: speed >= 1
    # If speed ends up being less than 1, then your default speed will be set to 1.
    speed: 1
