name: CoinAPI
version: 1.0
api: 3.0.0
main: CoinAPI\Main
author: [KAIDOZ, NhanAZ]
commands:
 helpcoin:
   description: "Hiển Thị Hướng Dẫn Sử Dụng Các Lệnh Liên Quan Tới Coin!"
 mycoin:
   description: "Xem Số Coin Của Bản Thân!"
 seecoin:
   description: "Xem Số Coin Của Người Chơi Khác!"
 paycoin:
   description: "Chuyển Coin Cho Người Chơi Khác!"
 doicoin:
   description: "Đổi Tiền Thành Coin!"
 topcoin:
   description: "Hiển Thị Bảng Xếp Hạng Coin!"
 setcoin:
   description: "Chỉnh Sửa Số Coin Của Người Chơi!"
 givecoin:
   description: "Cộng Thêm Coin Vào Tài Khoản Người Chơi!"
 takecoin:
   description: "Trừ Bớt Coin Của Tài Khoản Người Chơi!"