---
# AutoClearLagg (ACL) Config

# Seconds between each clear lagg
seconds: 300

# Entities to clear
clear:
  items: true
  mobs: true
  exempt: # Array of entities not to clear
 

messages:
  time-left: "§l§2♻§f Còn §e{SECONDS} §fgiây nữa là xóa toàn bộ vật phẩm"
  entities-cleared: "§l§2♻ §fĐã xóa toàn bộ vật phảm cho máy chủ §a✔"

# Countdown times
times: [60]
...
